.TH simple-pomodoro 1 "October 2024" "Version 1.0" "Manual"
.SH NAME
simple-pomodoro  \- a simple pomodoro timer for the terminal.
.SH SYNOPSIS
.B simple-pomodoro [OPTIONS]
.SH DESCRIPTION
Set a pomodoro session from the command line and output the timer to stdout.
.TP
.B \-h, --help
Show help message
